


exec-once = hyprctl setcursor 'Sweet-cursors' 20
# env = XCURSOR_SIZE,40
# env = HYPRCURSOR_THEME,Sweet-cursors
# env = HYPRCURSOR_SIZE,20
# exec-once = gsettings set org.gnome.desktop.interface cursor-theme 'Sweet-cursors'

